### ISSUE TITLE
2.2.d As a developer I want to create a good command line interface by using an external library

### ISSUE THREAD

**Issue by EmmaAndrea** [ITU-BDSA2024-GROUP28/Chirp#3]
Acceptance Criteria:
- Create feature branch
- Use a strong external library (docopt)
- Understand library sufficiently to implement for our needs
- Make sure arguments passed to the program are not manually parsed out of the args property.
- Provides the options read and write
- Returns useful information to parse into database
- Merge feature branch
- Close feature branch

**Comment by Jvascs** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer
