### ISSUE TITLE
As a developer I need to Depend on Abstractions by removing the database from Chirp.CLI (2.b)

### ISSUE THREAD

**Issue by EmmaAndrea** [ITU-BDSA2024-GROUP28/Chirp#4]
Acceptance Criteria:
- The database must be in a separate project
- We must have an interface IDatabaseRepository which is generic
- We must have a single class which uses this interface
- We must add a reference to the new DB project through the terminal
- "dotnet add [<PROJECT>] reference"
- Make sure to seal class CSVDatabase<T> by specifying in C#:
- "sealed class CSVDatabase<T> {}"

**Comment by JoelMoraes77** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by EmmaAndrea** [comment]
Summary:
After the refactoring, it should be as follows: 
A generic class CSVDatabase<T> implements the generic interface IDatabaseRepository<T> 
and the two methods Read and Store. 
A reference to the database is used in the main program class 
so that cheeps can be stored to the database and be retrieved from it.
